---
- name: "Install prerequisites"
  apt: 
    name: "{{item}}"
    state: latest
  loop:
    - apt-transport-https
- name: "Add Elasticstack repository key"
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
- name: "Add Elasticstack repository"
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
- name: "Install Elasticsearch"
  apt:
    name: elasticsearch
    state: latest
  notify: "notify elasticsearch for restart"
- name: "Tune sysctl vm.max_map_count and reload"
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
- name: "Allow local network connections"
  lineinfile: 
    dest: /etc/elasticsearch/elasticsearch.yml
    state: present 
    line: 'network.host: ["{{ ansible_default_ipv4.address }}", "localhost"]'
  notify: "notify elasticsearch for restart"
- name: "Allow local network connections part 2"
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    state: present
    line: 'discovery.seed_hosts: []'
  notify: "notify elasticsearch for restart"
