---
- name: Add Elasticsearch repository
  yum_repository:
    name: elasticsearch-5.x
    description: Elasticsearch repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Add Elasticsearch key to keystore
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Install java
  yum: 
    name: java
    state: latest
- name: Install Elasticsearch 
  yum:
    name: elasticsearch
    state: latest
- name: allow local network connections
  lineinfile: 
    dest: /etc/elasticsearch/elasticsearch.yml
    state: present 
    line: 'network.host: ["{{ ansible_default_ipv4.address }}", "localhost"]'
  notify: "notify elasticsearch for restart"
